# Copyright 2024 Brandon Nguyen
# SPDX-License-Identifier: Apache-2.0
build = 'Soong'

# Base project config which contain shared attributes which
# all other projects must contain / override
[project_config]
name = 'android_aarch64_drivers'

[project_config.host_machine]
build_machine = 'linux'
host_machine = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'

[project_config.meson_options]
vulkan-drivers="gfxstream" 
gallium-drivers="" 
opengl=false
