# Copyright 2024 Brandon Nguyen
# SPDX-License-Identifier: Apache-2.0
build = 'Soong'

# Base project config which contain shared attributes which
# all other projects must contain / override
[project_config]
name = 'android_aarch64_drivers'

# minimum_literal = {'cpu', 'cpu_family', 'endian', 'system'}
[project_config.host_machine]
cpu = 'aarch64'
cpu_family = 'aarch64'
system = 'android'
endian = 'little'

# If host/build machine are empty, the script will default to the native
# machine specs
[project_config.build_machine]
# cpu = 'aarch64'
# cpu_family = 'aarch64'
# system = 'linux'
# endian = 'little'

[project_config.meson_options]
vulkan-drivers="gfxstream" 
gallium-drivers="" 
opengl=false
