# Copyright 2024 Brandon Nguyen
# SPDX-License-Identifier: Apache-2.0
build = 'Soong'

# Base project config which contain shared attributes which
# all other projects must contain / override
[project_config]
name = 'android_aarch64_drivers'

[project_config.host_machine]
cpu_family = 'aarch64'
cpu = 'aarch64'
host_machine = 'android'
build_machine = 'linux'

[project_config.meson_options]
vulkan-drivers="gfxstream" 
gallium-drivers="" 
opengl=false
# platforms = 'android'
# android-libbacktrace = 'disabled'
# gallium-drivers = ''
# vulkan-drivers = 'freedreno,gfxstream'
# freedreno-kmds = 'kgsl'
# platform-sdk-version = 33
